### ISSUE TITLE
Feature request: Support tags in YAML frontmatter

### ISSUE THREAD

**Issue by fkirkholt** [blakedietz/vscode-nested-tags#18]
For instance `tags: [topic,example]`

Would also make the tags compatible with [Notable](https://github.com/fabiospampinato/notable)

**Comment by blakedietz** [comment]
This is the next feature I’ll work on. Keep logging issues if you have any more ideas.

**Comment by fkirkholt** [comment]
Great, but you don't quite follow the yaml standard. In yaml lists should be sorrounded by square brackets, or listed like an unordered list. 

`tags: [tag1, tag2]`

or 

```
tags:
    - tag1
    - tag2
```

**Comment by blakedietz** [comment]
Derp, I got excited and did this over lunch. Should uhh have looked at the yaml spec. My bad. A fix is coming soon™.

**Comment by noraj** [comment]
@blakedietz Thanks a lot, that was totally what I was looking for! I added it to https://alternativeto.net/software/vscode-nested-tags/ (pending, will be accepted soon)
