### ISSUE TITLE
Feature request: List files with path relative to opened folder

### ISSUE THREAD

**Issue by fkirkholt** [blakedietz/vscode-nested-tags#19]
The path should be relative to the project, and not the root. Maybe show them the way the search panel shows the files, with the path after the file name. The way it works now, I just see the first part of the path, and not the file names.

**Comment by blakedietz** [comment]
:) I absolutely agree with this.

**Comment by c-adkins** [comment]
This is my top requested feature. Great work so far @blakedietz ! Thank you!

**Comment by blakedietz** [comment]
@c-adkins @fkirkholt thank you for the feedback. This will be the next feature I work on.
