### ISSUE TITLE
Feature Request: Support other file extensions

### ISSUE THREAD

**Issue by pranphy** [blakedietz/vscode-nested-tags#44]
It appears to me that only `.md` files are scanned for tags. It would be great if I could add tags on other file extensions. Like on `.tex` files `% @nested-tags:topic,here/is/a/nested/example`.

**Comment by blakedietz** [comment]
You sir are very disciplined to keep your notes in LaTeX. :) Yeah, we can do that!

**Comment by blakedietz** [comment]
@pranphy I've got a branch out right now to address this feature request. I'll add some documentation and do some more testing before I release it. You can see that [here](https://github.com/blakedietz/vscode-nested-tags/tree/feature/add-file-type-support).

**Comment by blakedietz** [comment]
Resolved by release https://github.com/blakedietz/vscode-nested-tags/tree/v1.6.0.
