### ISSUE TITLE
Bug: Orphaned link in nested tag after renaming file

### ISSUE THREAD

**Issue by EupraxiaCM** [blakedietz/vscode-nested-tags#48]
#### Issue description
After renaming a .md file, there is an orphaned link to the previous filename in my tag tree. Clicking the broken link throws a file not found error, but I am unable to remove the old link

#### Steps to reproduce the issue

1.  Increase tree level by 1 in markdown directive within .md file i.e.:
 --> 

2. Rename file - Previous filename should still be visible in tag tree i.e.
snippets.md -> adhoc-sftp.md
 
3. ~~Profit???~~ Error when you click the broken link in tag tree, no way to remove broken link

#### What's the expected result?

- Link to previous filename disappears after renaming file

#### What's the actual result?

- Broken link to old filename remains after renaming file

#### Additional details / screenshot

-  ![nested tag bug report](https://user-images.githubusercontent.com/8031380/64998428-5d68e300-d8a1-11e9-9daf-372256ba9ae0.png)

- ![image](https://user-images.githubusercontent.com/8031380/64999107-d1a48600-d8a3-11e9-83b4-ebbebeb88b8f.png)

Edit: I  read the extension is untested on Windows, feel free to close if unsupported.

Thanks and I love the extension :P

**Comment by blakedietz** [comment]
Thanks for the writeup. I'll look into it. <3

**Comment by blakedietz** [comment]
Was able to reproduce on macOS as well. So this is definitely not a Windows specific bug. Not surprised by that either considering the API is abstracted over the operating system anyway.

**Comment by blakedietz** [comment]
Fixed on macOS with 93bda9197ae7cd47a9122b9ef2a298c47bedf724. Let me know if the issue still exists for M$.
