### ISSUE TITLE
Duplicate Tags in Tag Tree

### ISSUE THREAD

**Issue by twstewart42** [blakedietz/vscode-nested-tags#59]
For some files with tags they are producing duplicate categories in the Tag Tree, such that 1 or 2 files is separate from the other tag. 

![image](https://user-images.githubusercontent.com/5286873/86356919-159e2700-bc3b-11ea-91d1-94d004f61918.png)

for example I have 2 files with the terraform tag each with the same exact line 
`<!--@nested-tags:terraform-->`
but as you can see this is producing duplicate tags in the tag tree. 

I tried copy/pasting the same line from one file to another and it made no difference. For other instances, it appears to be order based like `<!--@nested-tags:writing,fiction,books,specific-name-->` and `<!--@nested-tags:writing,fiction,specific-name,books-->` I had to re-arrange tags so that tags were in the same order on all files.

Running VScode 1.46.1, OS Win 10, Nested Tags v1.7.0

**Comment by twstewart42** [comment]
Doing more experiments and this might be a conflict between another extension, both fighting over the last line

**Comment by twstewart42** [comment]
Moving the `<!--@nested-tags:terraform-->` (and all other nested-tag lines) to the very first line fixed my problem.

**Comment by aisbergde** [comment]
it is not fixed:
![image](https://user-images.githubusercontent.com/9020187/192597061-d944e108-b314-45dc-84ab-09272d701779.png)

The difference is:
in test.vcode-nested-tags.2.md it is **not** the last line of the document.
`<!--@nested-tags:topic,here/is/a/nested/example-->`

![image](https://user-images.githubusercontent.com/9020187/192598088-119dfbce-b80c-4d2e-9a82-7bc2416edc88.png)

but in  test08.md it is the last line
![image](https://user-images.githubusercontent.com/9020187/192598156-d9208a0f-b4cd-439b-a85b-16162f82c7d3.png)

and here YAML syntax is used:
![image](https://user-images.githubusercontent.com/9020187/192598343-1f7afd57-12d2-4f24-b61e-cb7df4ae4ced.png)
