### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by kevinslin** [blakedietz/vscode-nested-tags#66]
Thanks for the great extension. Wanted to ask what the license was since I didn't see it in the repo

**Comment by blakedietz** [comment]
https://github.com/blakedietz/vscode-nested-tags/blob/master/LICENSE

MIT. Didn't have one in there. Added it. Any plans? :)

**Comment by kevinslin** [comment]
I'm the author of a note taking extension inside vscode: http://dendron.so/

We're looking to add better tag support, possibly by bundling an extension that already does it well. That's why I asked :)

**Comment by blakedietz** [comment]
Ah, very nice app! Well, if you think it would work, go right ahead and let me know! If not, no worries.

However, I'm not sure how well it would fit in to other projects strictly from a reusability perspective. I do have an issue open for writing a 2.0.0 version that uses proper ast parsing to enrich the underlying data structures. This should make some of the other feature requests people have logged a bit simpler to implement.
