### ISSUE TITLE
Plugin not working on Win10

### ISSUE THREAD

**Issue by Didgety** [blakedietz/vscode-nested-tags#83]
With either entry saved in notes.md, tag explorer does not populate, am I doing something wrong? I have tried removing the date field as well
```
# Daily Task Notes

## Entry 1

---

tags: [First Entry, Note Test, Confluence, JIRA, Ping Down]
date: 10/9/2021

---

notes go here
```

OR

```
# Daily Task Notes

## Entry 1

---
tags: [First Entry, Note Test, Confluence, JIRA, Ping Down]
date: 10/9/2021
---

notes go here
```

**Comment by per1234** [comment]
This is front matter:
```yaml
---

tags: [First Entry, Note Test, Confluence, JIRA, Ping Down]
date: 10/9/2021

---
```
The "front" in "front matter" means it must be at the top of the document. You don't have it at the top of the document, so it is not recognized.

If you want to define tags at arbitrary locations in the document, then use the HTML comment style as shown here:
https://github.com/blakedietz/vscode-nested-tags#features
